[package]
name = "fast_morse_smale"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.15.0"
flume = "0.11.0"
image = "0.25.1"
wgpu = "0.19"

[dev-dependencies]
pollster = { version = "0.3", features = ["macro"] }
