[package]
name = "fast_morse_smale_2d"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.15"
flume = "0.11"
wgpu = "0.19"

[dev-dependencies]
pollster = { version = "0.3", features = ["macro"] }
